#!/bin/bash
export QT_QPA_PLATFORMTHEME=qt5ct &
xset s off -dpms &
dbus-update-activation-environment --systemd --all &
if ! pgrep -x "polkit-gnome-authentication-agent-1" > /dev/null; then
    /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
fi
